"""add secondary_email

Revision ID: 3ed4ac7724a6
Revises: 
Create Date: 2026-02-04 18:57:45.295918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ed4ac7724a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('secondary_email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.drop_index(batch_op.f('unique_secondary_email'))
        batch_op.create_index(batch_op.f('ix_users_secondary_email'), ['secondary_email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_secondary_email'))
        batch_op.create_index(batch_op.f('unique_secondary_email'), ['secondary_email'], unique=True)
        batch_op.alter_column('secondary_email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
